# Generated by Django 2.1.7 on 2020-02-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200212_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='abstract',
            field=models.TextField(default=None, help_text='文章标签', verbose_name='摘要'),
        ),
    ]
