# Generated by Django 2.1.7 on 2020-02-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.CharField(help_text='文章标题', max_length=21845, verbose_name='文章内容'),
        ),
    ]
