# Generated by Django 2.1.7 on 2020-02-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200212_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(help_text='文章标题', verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.TextField(help_text='评论', verbose_name='评论'),
        ),
    ]
